config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :brands
  resources :sale_items
  resources :sales
  resources :clients
  resources :stocks
  resources :products
  resources :suppliers
  resources :categories
  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  draw(:admin)

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get 'versions/:model_name', to: 'versions#index', as: 'index_versions'
    get 'versions/:model_name/:id', to: 'versions#show', as: 'show_version'

    draw(:home)

    concern :commenteable do
      resources :comments, only: %i[index create destroy]
    end

    devise_for :users, controllers: { confirmations: 'users/confirmations' }

    resources :global_settings, only: %i[index edit update]
    resources :users, path: '/admin/users', concerns: :commenteable
    resources :notifications, only: [:index] do
      post 'mark_read', on: :member
      post 'mark_all_read', on: :collection
    end
    root to: 'home#index'
  end

  draw(:react)

  get '/:locale' => 'home#index', locale: /#{I18n.available_locales.join('|')}/
end

app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  include PgSearch::Model
  has_many :products
  has_paper_trail

  def to_s
    super
  end

  def self.search(search, page)
    if search.present?
      paginate(per_page: 20, page:).full_search(search)
    else
      paginate(per_page: 20, page:)
    end
  end

  pg_search_scope(
    :full_search,
    against: %i[name],
    associated_against: {}, # relation: %i[f1, f2], another: %i[f1, f2]
    using: { tsearch: { prefix: true } },
    ignoring: :accents
  )
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# CategoriesController
class CategoriesController < ApplicationController
  load_and_authorize_resource

  # GET /categories
  # GET /categories.json
  def index
    @q = @categories.ransack(params[:q])
    @q.sorts = 'id desc' if @q.sorts.empty?
    @categories = @q.result
    @categories = @categories.order(:id).search(params[:pgq], params[:page])
    return unless params[:select2]

    select2_render
  end

  # GET /categories/1
  # GET /categories/1.json
  def show; end

  # GET /categories/new
  def new; end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  # POST /categories.json
  def create
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "#{t('activerecord.models.category.one')} criado com sucesso" }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "#{t('activerecord.models.category.one')} atualizado com sucesso." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    sanitize_active_storage_params(Category, @category)
    params.require(:category).permit(:name)
  end

  def select2_render
    render json: Oj.dump(
      {
        results: @categories.map { |category| { text: category.to_s, id: category.id } },
        pagination: { more: @categories.next_page.present? }
      }, mode: :compat
    )
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= semantic_form_for @category, html: { class: 'form-row' } do |f| %>
  <%= f.input :name, class: 'col-12' %>
  <%= f.action :submit, label: t('activerecord.link.save'), as: :button, class: 'col-12', html: { 'data-disable-with' => t('activerecord.link.sending') } %>
<% end %>

app/views/categories/edit.html.erb
<header class="content__title">
  <h1><%= t('helpers.submit.general.edit', model: t('activerecord.models.category.one')) %></h1>
  <div class="actions">
    <%= link_to '', categories_path, title: t('activerecord.link.back_to_list'), class: 'actions__item zmdi zmdi-arrow-left' %>
    <%= link_to '', @category, title: t('activerecord.link.details'), class: 'actions__item zmdi zmdi-search' %>
    <%= link_to '', '', title: t('Refresh'), class: 'actions__item zmdi zmdi-refresh-alt' %>
  </div>
</header>
<div class="card">
  <div class="card-body card-padding record">
		<%= render 'form' %>
	</div>
</div>

app/views/categories/index.html.erb
<header class="content__title">
  <h1>
    <%= t('activerecord.models.category.other') %>
    <% if controller_name == "versions" %>
      <small style="color: red">
        <%= t('helpers.scaffold.deleted_warning') %>
      </small>
    <% end %>
  </h1>

  <div class="actions">
    <%= link_to '', categories_path, title: t('activerecord.link.back_to_list'), class: 'actions__item zmdi zmdi-arrow-left' if controller_name == 'versions' %>
    <%= link_to '', '', title: t('activerecord.link.refresh'), class: 'actions__item zmdi zmdi-refresh-alt' %>
    <%= link_to '', new_category_path, title: t('activerecord.link.add_new'), class: 'actions__item zmdi zmdi-plus' if can?(:new, Category) && controller_name != 'versions' %>
  </div>
</header>
<div class="card">
  <div class="card-body card-padding">
    <%= render 'layouts/search' unless controller_name == "versions" %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <%# As we use this view to show deleted records, we check if it's %>
            <%# the versions controller to show an extra column %>
          <% if controller_name == "versions" %>
            <th style="color: red"><%= t('helpers.scaffold.deleted_at') %></th>
          <% end %>
            <%# If there's a @q, ransack is started. Otherwise, normal translated text %>
            <th><%= if @q then sort_link(@q, :name) else t('activerecord.attributes.category.name') end %></th>
            <th class="actions-column"></th>
          </tr>
        </thead>
        <tbody>
          <% if @categories.empty? %>
            <tr>
              <td colspan="99" class="text-center"><%= t('helpers.scaffold.no_records') %></td>
            </tr>
          <% end %>
          <%# If we're in version controller, we need to reify each element %>
          <% (controller_name == 'versions' ? @categories.map(&:reify) : @categories).each do |category| %>
            <tr>
            <% if controller_name == "versions" %>
              <td style="color: red"><%= category.version.created_at %></td>
            <% end %>
              <td><%= category.name %></td>
              <td class="actions-column actions">
                <%= link_to '', (category.version.present? ? show_version_path(model_name: "categories", id: category.version.id) : category), title: t("activerecord.link.details"), class: "zmdi zmdi-search actions__item" %>
                <%= link_to '', edit_category_path(category), title: t("activerecord.link.edit"), class: "zmdi zmdi-edit actions__item" if can? :edit, category %>
                <%= link_to '', category, title: t("activerecord.link.destroy"), class: "zmdi zmdi-delete actions__item", method: :delete, data: { confirm: t('activerecord.link.destroy_confirm') } if can? :destroy, category %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= will_paginate @categories, class: "apple_pagination", previous_label: t('activerecord.link.previous'), next_label: t('activerecord.link.next') %>
    <br/>
    <div class="text-center">
      <%= link_to index_versions_path(model_name: "categories"), style: "color: red" do %>
        <%= t('helpers.scaffold.deleted_records') %>
      <% end if can?(:read, :deleted_records) && controller_name != "versions" %>
    </div>
  </div>
  <br>
</div>

app/views/categories/new.html.erb
<header class="content__title">
  <h1><%= t('helpers.submit.general.new', model: t('activerecord.models.category.one')) %></h1>
  <div class="actions">
    <%= link_to '', categories_path, title: t('activerecord.link.back_to_list'), class: 'actions__item zmdi zmdi-arrow-left' %>
    <%= link_to '', '', title: t('Refresh'), class: 'actions__item zmdi zmdi-refresh-alt' %>
  </div>
</header>
<div class="card">
  <div class="card-body card-padding record">
		<%= render 'form' %>
	</div>
</div>

app/views/categories/show.html.erb
<header class="content__title">
  <h1>
    <%= t('helpers.submit.general.show', model: t('activerecord.models.category.one')) %>
  </h1>

  <div class="actions">
    <%= link_to '', (controller_name == "versions" ? index_versions_path(model_name: "categories") : categories_path), title: t('activerecord.link.back_to_list'), class: 'actions__item zmdi zmdi-arrow-left' %>
    <%= link_to '', '', title: t('activerecord.link.refresh'), class: 'actions__item zmdi zmdi-refresh-alt' %>
    <%= link_to '', edit_category_path(@category), title: t('activerecord.link.edit'), class: 'actions__item zmdi zmdi-edit' if can?(:edit, @category) && controller_name != 'versions' %>
  </div>
</header>
<div class="card">
  <div class="card-body card-padding record-show">
    <div class="row">
        <div class="col-12">
          <label class="fg-label"><%= t('activerecord.attributes.category.name') %></label><br/>&nbsp;
          <%= @category.name %>
        </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <label class="fg-label"><%= t('activerecord.attributes.category.created_at') %></label><br/>&nbsp;
        <%= @category.created_at %>
      </div>
      <div class="col-sm-6">
        <label class="fg-label"><%= t('activerecord.attributes.category.updated_at') %></label><br/>&nbsp;
        <%= @category.updated_at %>
      </div>
    </div>
  </div>
</div>
<%= render partial: "layouts/record_changes", locals: { :@object => @category } %>