config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :brands
  resources :sale_items
  resources :sales
  resources :clients
  resources :stocks
  resources :products
  resources :suppliers
  resources :categories
  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  draw(:admin)

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get 'versions/:model_name', to: 'versions#index', as: 'index_versions'
    get 'versions/:model_name/:id', to: 'versions#show', as: 'show_version'

    draw(:home)

    concern :commenteable do
      resources :comments, only: %i[index create destroy]
    end

    devise_for :users, controllers: { confirmations: 'users/confirmations' }

    resources :global_settings, only: %i[index edit update]
    resources :users, path: '/admin/users', concerns: :commenteable
    resources :notifications, only: [:index] do
      post 'mark_read', on: :member
      post 'mark_all_read', on: :collection
    end
    root to: 'home#index'
  end

  draw(:react)

  get '/:locale' => 'home#index', locale: /#{I18n.available_locales.join('|')}/
end

app/models/product.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: products
#
#  id           :bigint           not null, primary key
#  cost         :decimal(, )
#  description  :text
#  name         :string
#  quantity     :integer
#  resale_price :decimal(, )
#  sku          :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  brand_id     :bigint           not null
#  category_id  :bigint           not null
#  supplier_id  :bigint           not null
#
class Product < ApplicationRecord
  belongs_to :category, required: true
  belongs_to :supplier, required: true
  belongs_to :brand, required: true
  has_one :stock
  has_many :sale_items
  has_many :sales, through: :sale_items
  has_one_attached :image
  include PgSearch::Model
  has_paper_trail

  after_save :create_or_update_stock

  def to_s
    super
  end

  def self.search(search, page)
    if search.present?
      paginate(per_page: 20, page:).full_search(search)
    else
      paginate(per_page: 20, page:)
    end
  end

  pg_search_scope(
    :full_search,
    against: %i[sku name description],
    associated_against: {}, # relation: %i[f1, f2], another: %i[f1, f2]
    using: { tsearch: { prefix: true } },
    ignoring: :accents
  )

  private

  def create_or_update_stock
    stock = Stock.find_or_initialize_by(product_id: id)
    stock.quantity = quantity
    stock.save
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# ProductsController
class ProductsController < ApplicationController
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
    @q = @products.ransack(params[:q])
    @q.sorts = 'id desc' if @q.sorts.empty?
    @products = @q.result
    @products = @products.order(:id).search(params[:pgq], params[:page])
    return unless params[:select2]

    select2_render
  end

  # GET /products/1
  # GET /products/1.json
  def show; end

  # GET /products/new
  def new; end

  # GET /products/1/edit
  def edit; end

  # POST /products
  # POST /products.json
  def create
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "#{t('activerecord.models.product.one')} criado com sucesso" }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "#{t('activerecord.models.product.one')} atualizado com sucesso." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    sanitize_active_storage_params(Product, @product)
    params.require(:product).permit(:sku, :name, :description, :quantity, :category_id, :resale_price, :supplier_id, :cost, :image, :brand_id)
  end

  def select2_render
    render json: Oj.dump(
      {
        results: @products.map { |product| { text: product.to_s, id: product.id } },
        pagination: { more: @products.next_page.present? }
      }, mode: :compat
    )
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= semantic_form_for @product, html: { class: 'form-row' } do |f| %>
  <%= f.input :sku, class: 'col-sm-4' %>
  <%= f.input :name, class: 'col-sm-4' %>
  <%= f.input :description, class: 'col-sm-12' %>
  <%= f.input :category, class: 'col-sm-4' %>
  <%= f.input :brand, class: 'col-sm-4' %>
  <%= f.input :quantity, class: 'col-sm-4' %>  
  <%= f.input :resale_price, class: 'col-sm-4' %>
  <%= f.input :supplier, class: 'col-sm-4' %>
  <%= f.input :cost, class: 'col-sm-4' %>
  <%= f.input :image, as: :image, direct_upload: true, class: 'col-12' %>
  <%= f.action :submit, label: t('activerecord.link.save'), as: :button, class: 'col-12', html: { 'data-disable-with' => t('activerecord.link.sending') } %>
<% end %>

app/views/products/edit.html.erb
<header class="content__title">
  <h1><%= t('helpers.submit.general.edit', model: t('activerecord.models.product.one')) %></h1>
  <div class="actions">
    <%= link_to '', products_path, title: t('activerecord.link.back_to_list'), class: 'actions__item zmdi zmdi-arrow-left' %>
    <%= link_to '', @product, title: t('activerecord.link.details'), class: 'actions__item zmdi zmdi-search' %>
    <%= link_to '', '', title: t('Refresh'), class: 'actions__item zmdi zmdi-refresh-alt' %>
  </div>
</header>
<div class="card">
  <div class="card-body card-padding record">
		<%= render 'form' %>
	</div>
</div>

app/views/products/index.html.erb
<header class="content__title">
  <h1>
    <%= t('activerecord.models.product.other') %>
    <% if controller_name == "versions" %>
      <small style="color: red">
        <%= t('helpers.scaffold.deleted_warning') %>
      </small>
    <% end %>
  </h1>

  <div class="actions">
    <%= link_to '', products_path, title: t('activerecord.link.back_to_list'), class: 'actions__item zmdi zmdi-arrow-left' if controller_name == 'versions' %>
    <%= link_to '', '', title: t('activerecord.link.refresh'), class: 'actions__item zmdi zmdi-refresh-alt' %>
    <%= link_to '', new_product_path, title: t('activerecord.link.add_new'), class: 'actions__item zmdi zmdi-plus' if can?(:new, Product) && controller_name != 'versions' %>
  </div>
</header>
<div class="card">
  <div class="card-body card-padding">
    <%= render 'layouts/search' unless controller_name == "versions" %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <%# As we use this view to show deleted records, we check if it's %>
            <%# the versions controller to show an extra column %>
          <% if controller_name == "versions" %>
            <th style="color: red"><%= t('helpers.scaffold.deleted_at') %></th>
          <% end %>
            <%# If there's a @q, ransack is started. Otherwise, normal translated text %>
            <th><%= if @q then sort_link(@q, :sku) else t('activerecord.attributes.product.sku') end %></th>
            <th><%= if @q then sort_link(@q, :image) else t('activerecord.attributes.product.image') end %></th>
            <th><%= if @q then sort_link(@q, :name) else t('activerecord.attributes.product.name') end %></th>
            <!--<th><%#= if @q then sort_link(@q, :description) else t('activerecord.attributes.product.description') end %></th>-->
            <th><%= if @q then sort_link(@q, :quantity) else t('activerecord.attributes.product.quantity') end %></th>
            <th><%= if @q then sort_link(@q, :category) else t('activerecord.attributes.product.category') end %></th>
            <th><%= if @q then sort_link(@q, :cost) else t('activerecord.attributes.product.cost') end %></th>            
            <th><%= if @q then sort_link(@q, :supplier) else t('activerecord.attributes.product.supplier') end %></th>
            <th><%= if @q then sort_link(@q, :resale_price) else t('activerecord.attributes.product.resale_price') end %></th>
            
            <th class="actions-column"></th>
          </tr>
        </thead>
        <tbody>
          <% if @products.empty? %>
            <tr>
              <td colspan="99" class="text-center"><%= t('helpers.scaffold.no_records') %></td>
            </tr>
          <% end %>
          <%# If we're in version controller, we need to reify each element %>
          <% (controller_name == 'versions' ? @products.map(&:reify) : @products).each do |product| %>
            <tr>
            <% if controller_name == "versions" %>
              <td style="color: red"><%= product.version.created_at %></td>
            <% end %>
              <td><%= product.sku %></td>
              
              <td><%= image_tag product.image, class: "product-image", size: "80x80" if product.image.attached? %></td>
                  
             

              <td><%= product.name %></td>
              <!--<td><%#= product.description %></td>-->
              <td><%= product.quantity %></td>
              <td><%= product.category.name %></td>
              <td><%= product.cost %></td>              
              <td><%= product.supplier.name %></td>
              <td><%= product.resale_price %></td>              
              <td class="actions-column actions">
                <%= link_to '', (product.version.present? ? show_version_path(model_name: "products", id: product.version.id) : product), title: t("activerecord.link.details"), class: "zmdi zmdi-search actions__item" %>
                <%= link_to '', edit_product_path(product), title: t("activerecord.link.edit"), class: "zmdi zmdi-edit actions__item" if can? :edit, product %>
                <%= link_to '', product, title: t("activerecord.link.destroy"), class: "zmdi zmdi-delete actions__item", method: :delete, data: { confirm: t('activerecord.link.destroy_confirm') } if can? :destroy, product %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= will_paginate @products, class: "apple_pagination", previous_label: t('activerecord.link.previous'), next_label: t('activerecord.link.next') %>
    <br/>
    <div class="text-center">
      <%= link_to index_versions_path(model_name: "products"), style: "color: red" do %>
        <%= t('helpers.scaffold.deleted_records') %>
      <% end if can?(:read, :deleted_records) && controller_name != "versions" %>
    </div>
  </div>
  <br>
</div>

app/views/products/new.html.erb
<header class="content__title">
  <h1><%= t('helpers.submit.general.new', model: t('activerecord.models.product.one')) %></h1>
  <div class="actions">
    <%= link_to '', products_path, title: t('activerecord.link.back_to_list'), class: 'actions__item zmdi zmdi-arrow-left' %>
    <%= link_to '', '', title: t('Refresh'), class: 'actions__item zmdi zmdi-refresh-alt' %>
  </div>
</header>
<div class="card">
  <div class="card-body card-padding record">
		<%= render 'form' %>
	</div>
</div>

app/views/products/show.html.erb
<header class="content__title">
  <h1>
    <%= t('helpers.submit.general.show', model: t('activerecord.models.product.one')) %>
  </h1>

  <div class="actions">
    <%= link_to '', (controller_name == "versions" ? index_versions_path(model_name: "products") : products_path), title: t('activerecord.link.back_to_list'), class: 'actions__item zmdi zmdi-arrow-left' %>
    <%= link_to '', '', title: t('activerecord.link.refresh'), class: 'actions__item zmdi zmdi-refresh-alt' %>
    <%= link_to '', edit_product_path(@product), title: t('activerecord.link.edit'), class: 'actions__item zmdi zmdi-edit' if can?(:edit, @product) && controller_name != 'versions' %>
  </div>
</header>
<div class="card">
  <div class="card-body card-padding record-show">
    <div class="row">
        <div class="col-12">
          <label class="fg-label"><%= t('activerecord.attributes.product.sku') %></label><br/>&nbsp;
          <%= @product.sku %>
        </div>
        <div class="col-12">
          <label class="fg-label"><%= t('activerecord.attributes.product.name') %></label><br/>&nbsp;
          <%= @product.name %>
        </div>
        <div class="col-12">
          <label class="fg-label"><%= t('activerecord.attributes.product.description') %></label><br/>&nbsp;
          <%= @product.description %>
        </div>
        <div class="col-12">
          <label class="fg-label"><%= t('activerecord.attributes.product.quantity') %></label><br/>&nbsp;
          <%= @product.quantity %>
        </div>
        <div class="col-12">
          <label class="fg-label"><%= t('activerecord.attributes.product.category') %></label><br/>&nbsp;
          <%= @product.category.name %>
        </div>
        <div class="col-12">
          <label class="fg-label"><%= t('activerecord.attributes.product.resale_price') %></label><br/>&nbsp;
          <%= @product.resale_price %>
        </div>
        <div class="col-12">
          <label class="fg-label"><%= t('activerecord.attributes.product.supplier') %></label><br/>&nbsp;
          <%= @product.supplier.name %>
        </div>
        <div class="col-12">
          <label class="fg-label"><%= t('activerecord.attributes.product.cost') %></label><br/>&nbsp;
          <%= @product.cost %>
        </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <label class="fg-label"><%= t('activerecord.attributes.product.created_at') %></label><br/>&nbsp;
        <%= @product.created_at %>
      </div>
      <div class="col-sm-6">
        <label class="fg-label"><%= t('activerecord.attributes.product.updated_at') %></label><br/>&nbsp;
        <%= @product.updated_at %>
      </div>
    </div>
    <div class="row">   
      <div class="col-sm-6">
        <label class="fg-label"><%= t('activerecord.attributes.product.image') %></label><br/>&nbsp;
        <%= link_to url_for(@product.image), data: { lightbox: true } do %>
          <%= image_tag url_for(thumb(@product.image)), style: "max-width: 300px; height: auto;" %>
        <% end if @product.image.attached? %>
      </div>
    </div>
  </div>  
</div>
<%= render partial: "layouts/record_changes", locals: { :@object => @product } %>