config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :brands
  resources :sale_items
  resources :sales
  resources :clients
  resources :stocks
  resources :products
  resources :suppliers
  resources :categories
  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  draw(:admin)

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get 'versions/:model_name', to: 'versions#index', as: 'index_versions'
    get 'versions/:model_name/:id', to: 'versions#show', as: 'show_version'

    draw(:home)

    concern :commenteable do
      resources :comments, only: %i[index create destroy]
    end

    devise_for :users, controllers: { confirmations: 'users/confirmations' }

    resources :global_settings, only: %i[index edit update]
    resources :users, path: '/admin/users', concerns: :commenteable
    resources :notifications, only: [:index] do
      post 'mark_read', on: :member
      post 'mark_all_read', on: :collection
    end
    root to: 'home#index'
  end

  draw(:react)

  get '/:locale' => 'home#index', locale: /#{I18n.available_locales.join('|')}/
end

app/models/sale.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: sales
#
#  id         :bigint           not null, primary key
#  date       :datetime
#  total      :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  client_id  :bigint
#  user_id    :bigint           not null
#
class Sale < ApplicationRecord
  belongs_to :user, required: true
  belongs_to :client, required: false
  has_many :sale_items
  has_many :products, through: :sale_items
  include PgSearch::Model
  has_paper_trail

  after_commit :update_product_quantities

  def to_s
    super
  end

  def self.search(search, page)
    if search.present?
      paginate(per_page: 20, page:).full_search(search)
    else
      paginate(per_page: 20, page:)
    end
  end

  pg_search_scope(
    :full_search,
    against: %i[],
    associated_against: {}, # relation: %i[f1, f2], another: %i[f1, f2]
    using: { tsearch: { prefix: true } },
    ignoring: :accents
  )

  def update_total
    total_amount = sale_items.sum(&:total)
    update(total: total_amount)
  end

  private

  def update_product_quantities    
    sale_items.each do |sale_item|
      product = Product.find(sale_item.product_id)
      new_quantity = product.quantity - sale_item.quantity
      product.update(quantity: new_quantity)
    end
  end
  
end

app/controllers/sales_controller.rb
# frozen_string_literal: true

# SalesController
class SalesController < ApplicationController
  load_and_authorize_resource

  # GET /sales
  # GET /sales.json
  def index
    @q = @sales.ransack(params[:q])
    @q.sorts = 'id desc' if @q.sorts.empty?
    @sales = @q.result
    @sales = @sales.order(:id).search(params[:pgq], params[:page])
    return unless params[:select2]

    select2_render
  end

  # GET /sales/1
  # GET /sales/1.json
  def show; end

  # GET /sales/new
  def new; end

  # GET /sales/1/edit
  def edit; end

  # POST /sales
  # POST /sales.json
  def create
    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: "#{t('activerecord.models.sale.one')} criado com sucesso" }
        format.json { render action: 'show', status: :created, location: @sale }
      else
        format.html { render action: 'new' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: "#{t('activerecord.models.sale.one')} atualizado com sucesso." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def sale_params
    sanitize_active_storage_params(Sale, @sale)
    params.require(:sale).permit(:date, :total, :user_id, :client_id)
  end

  def select2_render
    render json: Oj.dump(
      {
        results: @sales.map { |sale| { text: sale.to_s, id: sale.id } },
        pagination: { more: @sales.next_page.present? }
      }, mode: :compat
    )
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= semantic_form_for @sale, html: { class: 'form-row' } do |f| %>
  <%= f.input :user, class: 'col-12' %>
  <%= f.input :client, class: 'col-12' %>
  <%= f.action :submit, label: t('activerecord.link.save'), as: :button, class: 'col-12', html: { 'data-disable-with' => t('activerecord.link.sending') } %>
<% end %>

app/views/sales/edit.html.erb
<header class="content__title">
  <h1><%= t('helpers.submit.general.edit', model: t('activerecord.models.sale.one')) %></h1>
  <div class="actions">
    <%= link_to '', sales_path, title: t('activerecord.link.back_to_list'), class: 'actions__item zmdi zmdi-arrow-left' %>
    <%= link_to '', @sale, title: t('activerecord.link.details'), class: 'actions__item zmdi zmdi-search' %>
    <%= link_to '', '', title: t('Refresh'), class: 'actions__item zmdi zmdi-refresh-alt' %>
  </div>
</header>
<div class="card">
  <div class="card-body card-padding record">
		<%= render 'form' %>
	</div>
</div>

app/views/sales/index.html.erb
<header class="content__title">
  <h1>
    <%= t('activerecord.models.sale.other') %>
    <% if controller_name == "versions" %>
      <small style="color: red">
        <%= t('helpers.scaffold.deleted_warning') %>
      </small>
    <% end %>
  </h1>

  <div class="actions">
    <%= link_to '', sales_path, title: t('activerecord.link.back_to_list'), class: 'actions__item zmdi zmdi-arrow-left' if controller_name == 'versions' %>
    <%= link_to '', '', title: t('activerecord.link.refresh'), class: 'actions__item zmdi zmdi-refresh-alt' %>
    <%= link_to '', new_sale_path, title: t('activerecord.link.add_new'), class: 'actions__item zmdi zmdi-plus' if can?(:new, Sale) && controller_name != 'versions' %>
  </div>
</header>
<div class="card">
  <div class="card-body card-padding">
    <%= render 'layouts/search' unless controller_name == "versions" %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <%# As we use this view to show deleted records, we check if it's %>
            <%# the versions controller to show an extra column %>
          <% if controller_name == "versions" %>
            <th style="color: red"><%= t('helpers.scaffold.deleted_at') %></th>
          <% end %>
            <%# If there's a @q, ransack is started. Otherwise, normal translated text %>
            <th><%= if @q then sort_link(@q, :id) else t('activerecord.attributes.sale.date') end %></th>
            <th><%= if @q then sort_link(@q, :date) else t('activerecord.attributes.sale.date') end %></th>            
            <th><%= if @q then sort_link(@q, :user) else t('activerecord.attributes.sale.user') end %></th>
            <th><%= if @q then sort_link(@q, :client) else t('activerecord.attributes.sale.client') end %></th>
            <th><%= if @q then sort_link(@q, :total) else t('activerecord.attributes.sale.total') end %></th>
            <th class="actions-column"></th>
          </tr>
        </thead>
        <tbody>
          <% if @sales.empty? %>
            <tr>
              <td colspan="99" class="text-center"><%= t('helpers.scaffold.no_records') %></td>
            </tr>
          <% end %>
          <%# If we're in version controller, we need to reify each element %>
          <% (controller_name == 'versions' ? @sales.map(&:reify) : @sales).each do |sale| %>
            <tr>
            <% if controller_name == "versions" %>
              <td style="color: red"><%= sale.version.created_at %></td>
            <% end %>
              <td><%= sale.id %></td>
              <td><%= sale.created_at %></td>              
              <td><%= sale.user %></td>
              <td><%= sale.client.name if sale.client.present? %></td>
              <td><%= sale.total %></td>
              <td class="actions-column actions">
                <%= link_to '', (sale.version.present? ? show_version_path(model_name: "sales", id: sale.version.id) : sale), title: t("activerecord.link.details"), class: "zmdi zmdi-search actions__item" %>
                <%= link_to '', edit_sale_path(sale), title: t("activerecord.link.edit"), class: "zmdi zmdi-edit actions__item" if can? :edit, sale %>
                <%= link_to '', sale, title: t("activerecord.link.destroy"), class: "zmdi zmdi-delete actions__item", method: :delete, data: { confirm: t('activerecord.link.destroy_confirm') } if can? :destroy, sale %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= will_paginate @sales, class: "apple_pagination", previous_label: t('activerecord.link.previous'), next_label: t('activerecord.link.next') %>
    <br/>
    <div class="text-center">
      <%= link_to index_versions_path(model_name: "sales"), style: "color: red" do %>
        <%= t('helpers.scaffold.deleted_records') %>
      <% end if can?(:read, :deleted_records) && controller_name != "versions" %>
    </div>
  </div>
  <br>
</div>

app/views/sales/new.html.erb
<header class="content__title">
  <h1><%= t('helpers.submit.general.new', model: t('activerecord.models.sale.one')) %></h1>
  <div class="actions">
    <%= link_to '', sales_path, title: t('activerecord.link.back_to_list'), class: 'actions__item zmdi zmdi-arrow-left' %>
    <%= link_to '', '', title: t('Refresh'), class: 'actions__item zmdi zmdi-refresh-alt' %>
  </div>
</header>
<div class="card">
  <div class="card-body card-padding record">
		<%= render 'form' %>
	</div>
</div>

app/views/sales/show.html.erb
<header class="content__title">
  <h1>
    <%= t('helpers.submit.general.show', model: t('activerecord.models.sale.one')) %>
  </h1>

  <div class="actions">
    <%= link_to '', (controller_name == "versions" ? index_versions_path(model_name: "sales") : sales_path), title: t('activerecord.link.back_to_list'), class: 'actions__item zmdi zmdi-arrow-left' %>
    <%= link_to '', '', title: t('activerecord.link.refresh'), class: 'actions__item zmdi zmdi-refresh-alt' %>
    <%= link_to '', edit_sale_path(@sale), title: t('activerecord.link.edit'), class: 'actions__item zmdi zmdi-edit' if can?(:edit, @sale) && controller_name != 'versions' %>
  </div>
</header>
<div class="card">
  <div class="card-body card-padding record-show">
    <div class="row">
        <div class="col-12">
          <label class="fg-label"><%= t('activerecord.attributes.sale.id') %></label><br/>&nbsp;
          <%= @sale.id %>
        </div>
        <div class="col-12">
          <label class="fg-label"><%= t('activerecord.attributes.sale.total') %></label><br/>&nbsp;
          <%= @sale.total %>
        </div>
        <div class="col-12">
          <label class="fg-label"><%= t('activerecord.attributes.sale.user') %></label><br/>&nbsp;
          <%= @sale.user %>
        </div>
        <div class="col-12">
          <label class="fg-label"><%= t('activerecord.attributes.sale.client') %></label><br/>&nbsp;
          <%= @sale.client.name if @sale.client.present? %> 
        </div> 
    </div>
    <div class="row">
      <div class="col-sm-6">
        <label class="fg-label"><%= t('activerecord.attributes.sale.created_at') %></label><br/>&nbsp;
        <%= @sale.created_at %>
      </div>
      <div class="col-sm-6">
        <label class="fg-label"><%= t('activerecord.attributes.sale.updated_at') %></label><br/>&nbsp;
        <%= @sale.updated_at %>
      </div>
    </div>
  </div>
</div>
<%= render partial: "layouts/record_changes", locals: { :@object => @sale } %>